version: '3'

services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: YourPassword 
    volumes:
     - mssql-volume:/var/opt/mssql
    ports:
      - '1433:1433'

volumes:
    mssql-volume: